### ISSUE TITLE
lus_open_fs.rst file missing from man Makefile

### ISSUE THREAD

**Issue by justinmiller** [fzago-cray/liblustre#1]
lus_open_fs.rst is not included in the Makefile, which results in a build failure:

make[2]: *** No rule to make target `lus_open_fs.3', needed by `all-am'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/jmiller/liblustre/rpms/BUILD/liblustre-0.2.0/man'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/jmiller/liblustre/rpms/BUILD/liblustre-0.2.0'
error: Bad exit status from /var/tmp/rpm-tmp.rFH159 (%build)

**Comment by justinmiller** [comment]
```
diff --git a/man/Makefile.am b/man/Makefile.am
index e863146..5000e14 100644
--- a/man/Makefile.am
+++ b/man/Makefile.am
@@ -35,6 +35,7 @@ EXTRA_DIST = \
        lus_hsm_action_begin.rst \
        lus_hsm_copytool_register.rst \
        lus_stat_by_fid.rst \
-       lus_mdt_stat_by_fid.rst
+       lus_mdt_stat_by_fid.rst \
+       lus_open_fs.rst
```

**Comment by fzago-cray** [comment]
Thanks Justin. This has been fixed some time ago. I didn't see this bug report.
